config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pools do
    get 'join', on: :member
    resources :entries
  end
  resources :pool_memberships
  root to: "welcome#index"
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :pool_memberships
  has_many :members, through: :pool_memberships, source: :user
  after_create :create_owner_pool_membership
  has_many :entries

  private

  def create_owner_pool_membership
    self.pool_memberships.create!(user_id: self.owner_id)
  end

  def create_user_pool_membership
    self.user.pool_memberships.create!(user_id: self.user.id)
  end

end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController

  def index
    @pools = Pool.all.reject {|p| !p.is_public }
  end

  def new
    @pool = Pool.new(owner_id: current_user.id)
  end

  def create
    @pool = Pool.create(pool_params)
    if @pool.save
      redirect_to root_path
    else
      flash[:error] = "You need to fill out the form"
      redirect_to :new
    end
  end

  def show
    @pool = Pool.find(params[:id])
    @users = @pool.members
  end

  def join
    pool = Pool.find(params[:id])
    pool.pool_memberships.build(user_id: current_user.id)
    if pool.save
      render 'show'
    else
      flash[:error] = "Oops"
      render 'show'
    end
  end

  private

  def pool_params
    params.require(:pool).permit(:owner_id, :is_public, :name)
  end
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/index.html.erb
<% @pools.each do |pool| %>
  <p>
    <%= link_to pool.name, pool %>
  </p>
<% end %>

app/views/pools/new.html.erb
<h2>Create a pool</h2>
<%= simple_form_for @pool do |f| %>
  <%= f.input :owner_id, as: :hidden %>
  <%= f.input :name %>
  <%= f.input :is_public, as: :boolean, input_html: { checked: true } %>
  <%= f.button :submit %>
<% end %>

app/views/pools/show.html.erb
<% unless @pool.members.exists?(current_user.id) %>
<%= link_to "Join pool", join_pool_path(@pool.id), class: "btn btn-primary" %>
<% end %>
<h1><%= @pool.name %></h1>

<% @pool.members.each do |user| %>
  <p>
    <%= user.email %> <%= link_to 'Create Entry' , pool_entries_path(@pool) if (user == current_user) %>
  </p>
<% end %>