config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pools do
    get 'join', on: :member
    resources :entries
  end
  resources :pool_memberships
  root to: "welcome#index"
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :pool
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
def index
  current_time = Time.now
  week = Football::Timeframe.where("start_date > ? and end_date > ? and api_season = ? and week > 0", current_time, current_time, "2017PRE").take
  @games = Football::Game.where(week: week.week, season_type: week.season_type)
  @games.each do |game|
    entry = Entry.where(
      user_id: current_user.id,
      pool_id: params[:pool_id],
      game_id: game.id).first_or_create
  end
  @entries = current_user.entries.where(pool_id: params[:pool_id])

end

def show
  @entry = Entry.find(params[:id])
end

def new
  @entry = Entry.new()
end

def create
  @entry = Entry.create(entry_params)
  if current_user
    @entry.save
  else
    redirect_to :new
  end
end

private

def entry_params
  params.require(:entry).permit(:team_id, :game_id )
end

end

app/views/entries/index.html.erb
<% @entries.each do |entry| %>
  <% game = @games.find_by(id: entry.game_id) %>
  <%= form_for pool_entry_path(id: params[:pool_id], entry_id: entry.id), method: :post do |f|%>
    <%= f.label game.home_team %>
    <%= f.radio_button game, "yes" %>
    <%= f.label game.away_team %>
    <%= f.radio_button game, "yes" %>
  <% end %>
<% end %>