config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pools do
    get 'join', on: :member
    resources :entries
  end
  resources :pool_memberships
  root to: "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Poolster</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <% if user_signed_in? %>
      <div class="container-fluid d-flex flex-row p-0 wrapper">
        <nav class="col-sm-3 col-md-2 hidden-xs-down sidebar bg-faded d-flex flex-column">
          <ul class="nav flex-column">
            <li class="nav-item">
              <%= link_to 'Pools', pools_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Rankings", '#', :class => 'nav-link' %>
            </li>
          </ul>
        <ul class="nav flex-column mt-auto">
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-link' %>
          </li>
        </ul>
      </nav>
      <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 ">
        <%= yield %>
      </div>
      <% else %>
      <div class="container-fluid flex-column p-0 d-flex wrapper">
        <nav class="navbar navbar-toggleable-md navbar-light">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">
              <%= "Poolster" %>
            </a>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, :class => 'nav-link' %>
              </li>
            </ul>
          </div>
        </nav>
        <%= yield %>
      <% end %>
    </div>
  </body>
</html>